name: Netlify Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '12'

      - name: Get node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-key: ${{ runner.os }}-build

      - name: Install node dependencies
        run: npm install

      - name: Build site with production mode
        run: npm run production
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_production
          path: build_production
