name: Netlify CD
on:
  workflow_run:
    workflows:
      - Netlify CI
    branches: [master]
    types:
      - completed

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
